title: US Disease Tracker Data Standards
description: Data standards and public documentation of the US Disease Tracker project
url: "https://usdiseasetracker.github.io"
baseurl: "/USDiseaseTracker-Docs"
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown

# Include/exclude files
include:
  - standards
  - examples-and-templates

exclude:
  - .git
  - .github
  - LICENSE
  - .gitignore

# Navigation (optional)
header_pages:
  - README.md
  - standards/README.md
  - examples-and-templates/README.md
  - CONTRIBUTING.md
