title: US Disease Tracker Data Standards
description: Data standards and public documentation of the US Disease Tracker project
theme: jekyll-theme-cayman
url: "https://usdiseasetracker.github.io"
baseurl: "/USDiseaseTracker-Docs"


# Build settings
markdown: kramdown

# Include/exclude files
include:
  - standards
  - templates
  - examples

exclude:
  - .git
  - .github
  - LICENSE
  - .gitignore

# Navigation (optional)
header_pages:
  - README.md
  - standards/README.md
  - templates/README.md
  - examples/README.md
  - CONTRIBUTING.md
